# Do not edit this file.  It is generated from:
#    /lustre/f2/pdata/ncep/Weiyu.Yang/tmp/isdffgd/isdffgd/ufs_new_work/ufs-s2s-model/standaloneFV3.appBuilder
# Edit that file instead.
COMPONENTS ?= FMS FV3
